---

- name: system packages | setup upstream nginx stable repo
  become: true
  yum:
    name: "https://nginx.org/packages/centos/7/noarch/RPMS/\
      nginx-release-centos-7-0.el7.ngx.noarch.rpm"
    state: present
  when: nginx_stable_repo

- name: system packages | setup upstream nginx mainline repo
  become: true
  copy:
    src: nginx-mainline.repo
    dest: /etc/yum.repos.d/nginx-mainline.repo
  when: not nginx_stable_repo

- name: system packages | install nginx
  become: true
  yum:
    name: >-
      nginx{{ (nginx_version | length > 0) |
        ternary('-' + nginx_version, '') }}
    state: present

# example_ssl.conf is in some distro versions but not upstream, disable it
# just in case
- name: nginx | remove default config
  become: true
  copy:
    content: "# This file is intentionally blank (Ansible)"
    dest: /etc/nginx/conf.d/{{ item }}
  with_items:
    - example_ssl.conf
    - default.conf
  when: not (nginx_keep_default_configs | default(False))
  notify:
    - restart nginx
